version: '3.8'

services:
  db:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    entrypoint:
      [
        "/surreal",
        "start",
        "-A",
        "--auth",
        "--user",
        "jocke",
        "--pass",
        "test"
      ]
